"""Auto-generated research report from a Registry run record.

Per v0.1 acceptance criterion #4: WARNINGs are AUTO-GENERATED from the
Registry's machine-readable trust fields — never hand-written. This is the
translation layer that turns `universe_meta.pit=false` + `bias_warning=[...]`
into a human-visible WARNING in every report.

Design note (why not reuse reporting/html_report.py): the existing reporting/
module targets portfolio-backtest result objects (HTML dashboard, performance
attribution, NAV curves). This generator targets a *run record* (one IC/ICIR/
DSR result + trust metadata) — a different abstraction level. Forcing reuse
would drag in portfolio-backtest dependencies for a single-factor IC slice.
This is justified separation, not a second system.
"""

from __future__ import annotations

import json
from pathlib import Path

WARN_PIT = (
    "This research run uses {provider} (PIT={pit}). "
    "Results may contain {biases}. Do NOT interpret as production alpha."
)


def _warnings_from_meta(run: dict) -> list[str]:
    """Build WARNING lines purely from Registry fields — no hardcoding here."""
    warns = []
    try:
        umeta = json.loads(run.get("universe_meta") or "{}")
        dmeta = json.loads(run.get("data_meta") or "{}")
    except json.JSONDecodeError:
        umeta, dmeta = {}, {}

    provider = umeta.get("provider", "unknown")
    pit = umeta.get("pit")
    biases = ", ".join(umeta.get("bias_warning", [])) or "unknown bias"

    # PIT honesty
    if pit is False:
        warns.append(
            WARN_PIT.format(provider=provider, pit=pit, biases=biases)
        )
    elif pit is None:
        warns.append(
            f"Universe PIT status UNDECLARED by provider '{provider}'. "
            "Treat results as unverified."
        )

    # Adjustment honesty
    adjust = dmeta.get("adjust")
    if adjust in (None, "none"):
        warns.append(
            f"Price data is NOT adjusted (adjust={adjust}). "
            "Corporate actions inject mechanical fake returns."
        )
    elif adjust == "front":
        basis = dmeta.get("basis", "unknown")
        warns.append(
            f"Front-adjusted prices (basis={basis}). Free-source front-adj "
            "uses a per-stock basis date; fine for cross-sectional ranking, "
            "caveat for absolute returns."
        )

    # Status honesty
    if run.get("status") == "failed":
        warns.append(
            f"RUN FAILED: {run.get('reason') or 'unspecified reason'}. "
            "No valid evaluation result — retained for negative knowledge."
        )

    return warns


def generate_report(run: dict, out_dir: str = "data/reports") -> str:
    """Write a Markdown report for a run. Returns the report path."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    warnings = _warnings_from_meta(run)
    try:
        evaluation = json.loads(run.get("evaluation") or "{}")
    except json.JSONDecodeError:
        evaluation = {}

    run_id = run.get("run_id", "unknown")
    lines = [
        f"# Research Run Report — {run_id}",
        "",
        f"- **Slice**: {run.get('slice', '?')}",
        f"- **Timestamp**: {run.get('timestamp', '?')}",
        f"- **Status**: {run.get('status', '?')}",
        f"- **Factor**: {run.get('factor', '?')}",
        f"- **Input hash (reproducibility)**: {run.get('input_hash', '?')}",
        "",
        "## ⚠️ Warnings (auto-generated from Registry trust fields)",
        "",
    ]
    if warnings:
        lines += [f"> **WARNING**: {w}" for w in warnings]
    else:
        lines.append("> (no warnings — all trust fields declared clean)")
    lines += [
        "",
        "## Data Lineage",
        f"- data_source: `{run.get('data_source', '?')}`",
        f"- data_meta: `{run.get('data_meta', '{}')}`",
        f"- universe_provider: `{run.get('universe_provider', '?')}`",
        f"- universe_meta: `{run.get('universe_meta', '{}')}`",
        "",
        "## Evaluation",
        "",
    ]
    if evaluation:
        for k, v in evaluation.items():
            lines.append(f"- **{k}**: {v}")
    else:
        lines.append("_(no evaluation — run may have failed before evaluation)_")
    lines += ["", f"_Generated by lab.reports.generator. Trust fields verbatim from Registry._", ""]

    path = out / f"{run_id}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)
