"""LLM Research Agent for automated strategy research.

Applies RAG-style architecture (Retrieve → Reason → Generate) to financial
research workflows:
- Extract signals from research reports, announcements, earnings calls
- Generate factor hypotheses from market narratives
- Summarize portfolio risk/return attribution in natural language
- Cross-reference news with factor data for alpha discovery

Architecture:
    Text Input → Chunking → Embedding/Keyword Extraction → Signal Extraction
         ↓                                                    ↓
    Factor Data ← Context Assembly ← Relevant Chunk Retrieval
         ↓
    LLM Reasoning → Structured Output (sentiment / hypothesis / summary)

This module demonstrates how Agent/RAG skills transfer directly to quant.

Usage:
    agent = ResearchAgent(api_key="sk-...")
    signals = agent.extract_signals_from_text(research_report, stock="600519")
    summary = agent.summarize_attribution(factor_contributions, daily_returns)
    hypotheses = agent.generate_hypotheses(market_narrative, factor_data)
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

import numpy as np
import pandas as pd

from quant_platform.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class ExtractedSignal:
    """A structured signal extracted from text."""
    stock: str
    signal_type: Literal["sentiment", "event", "hypothesis", "risk"]
    direction: Literal["bullish", "bearish", "neutral"]
    strength: float  # -1 to 1
    confidence: float  # 0 to 1
    reasoning: str
    source_text: str
    factor_implications: dict[str, float] = field(default_factory=dict)


@dataclass
class FactorHypothesis:
    """A factor hypothesis generated by the LLM."""
    factor_name: str
    description: str
    expected_ic: float
    economic_logic: str
    data_requirements: list[str]
    risk_factors: list[str]
    confidence: float


class ResearchAgent:
    """LLM-powered research agent for quantitative strategy research.

    Uses RAG-pattern: retrieve context → reason with LLM → structured output.

    Modes:
    - keyword: Zero-cost keyword extraction (default, for demo)
    - llm: Real OpenAI API calls (requires api_key)

    Examples:
        # Analyze a research report
        agent = ResearchAgent()
        signals = agent.extract_signals_from_text(
            "茅台Q3净利润同比增长30%，超出市场预期...",
            stock="600519"
        )

        # Generate factor hypotheses from market narrative
        hypotheses = agent.generate_hypotheses(
            "近期新能源板块资金持续流入，光伏装机量超预期...",
            available_factors=["momentum", "volatility", "turnover"]
        )

        # Summarize portfolio attribution in natural language
        summary = agent.summarize_attribution(
            {"momentum": 0.003, "value": -0.001, "size": 0.002},
            daily_returns
        )
    """

    def __init__(
        self,
        api_key: str | None = None,
        model: str = "gpt-4o-mini",
        mode: Literal["keyword", "llm"] = "keyword",
        cache_dir: str | None = None,
    ):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model
        self.mode = mode if not (mode == "llm" and not self.api_key) else "keyword"
        self.cache_dir = Path(cache_dir) if cache_dir else Path("./.agent_cache")
        self.cache_dir.mkdir(exist_ok=True)
        self._client = None
        self._cache: dict[str, Any] = {}

    # ──────────────────────────────────────────────────────────────
    # Core: Extract signals from research text
    # ──────────────────────────────────────────────────────────────

    def extract_signals_from_text(
        self,
        text: str,
        stock: str = "",
        source_type: str = "research_report",
    ) -> list[ExtractedSignal]:
        """Extract structured trading signals from unstructured financial text.

        Args:
            text: Research report, news article, or announcement text
            stock: Stock code if known
            source_type: Type of source (research_report, announcement, news)

        Returns:
            List of ExtractedSignal objects
        """
        # Chunk long text
        chunks = self._chunk_text(text, max_chars=2000)
        all_signals = []

        for chunk in chunks:
            if self.mode == "llm":
                signals = self._extract_signals_llm(chunk, stock, source_type)
            else:
                signals = self._extract_signals_keyword(chunk, stock)
            all_signals.extend(signals)

        # Deduplicate
        return self._deduplicate_signals(all_signals)

    def _extract_signals_keyword(self, text: str, stock: str) -> list[ExtractedSignal]:
        """Keyword-based signal extraction (zero cost, deterministic)."""
        signals = []

        # Financial metric extraction patterns
        patterns = {
            "revenue_growth": (r"营[业收].*?增[长速][\s:：]*(\d+\.?\d*)%", "bullish"),
            "profit_growth": (r"净利[润润].*?增[长速][\s:：]*(\d+\.?\d*)%", "bullish"),
            "profit_decline": (r"净利[润润].*?[下下]降[\s:：]*(\d+\.?\d*)%", "bearish"),
            "pe_ratio": (r"[市PE][E盈].*?(\d+\.?\d*)倍", None),
            "target_price": (r"目标价[\s:：]*(\d+\.?\d*)元", None),
            "buyback": (r"回购.*?(\d+\.?\d*)[亿万]", "bullish"),
            "dividend_yield": (r"[股分][息红].*?(\d+\.?\d*)%", "bullish"),
        }

        for metric_name, (pattern, default_dir) in patterns.items():
            match = re.search(pattern, text)
            if match:
                value = float(match.group(1))
                if default_dir:
                    direction = default_dir
                    strength = min(1.0, value / 100) if value > 0 else 0.3
                else:
                    direction = "neutral"
                    strength = 0.0

                signals.append(ExtractedSignal(
                    stock=stock,
                    signal_type="event",
                    direction=direction,
                    strength=strength if direction == "bullish" else -strength,
                    confidence=0.6,
                    reasoning=f"Extracted {metric_name}={value} from text",
                    source_text=text[:200],
                    factor_implications=self._infer_factor_implications(metric_name, value),
                ))

        # Sentiment keywords
        sentiment_score = self._keyword_sentiment(text)
        if abs(sentiment_score) > 0.2:
            signals.append(ExtractedSignal(
                stock=stock,
                signal_type="sentiment",
                direction="bullish" if sentiment_score > 0 else "bearish",
                strength=abs(sentiment_score),
                confidence=0.5,
                reasoning=f"Keyword sentiment score: {sentiment_score:.2f}",
                source_text=text[:200],
            ))

        return signals

    def _extract_signals_llm(
        self, text: str, stock: str, source_type: str
    ) -> list[ExtractedSignal]:
        """LLM-based signal extraction (higher quality, costs money)."""
        prompt = f"""Analyze this Chinese financial text and extract trading signals.

Text ({source_type}):
{text[:1500]}

Stock: {stock}

Output a JSON array of signals. Each signal has:
- signal_type: "sentiment" | "event" | "hypothesis" | "risk"
- direction: "bullish" | "bearish" | "neutral"
- strength: float -1.0 to 1.0
- confidence: float 0.0 to 1.0
- reasoning: brief explanation in Chinese
- factor_implications: dict of factor_name -> expected_impact (-1 to 1)

Output ONLY valid JSON array, no other text."""

        try:
            result = self._call_llm(prompt)
            data = json.loads(result)
            return [
                ExtractedSignal(
                    stock=stock,
                    signal_type=item.get("signal_type", "sentiment"),
                    direction=item.get("direction", "neutral"),
                    strength=item.get("strength", 0),
                    confidence=item.get("confidence", 0.5),
                    reasoning=item.get("reasoning", ""),
                    source_text=text[:200],
                    factor_implications=item.get("factor_implications", {}),
                )
                for item in data if isinstance(item, dict)
            ]
        except Exception as e:
            logger.warning("LLM signal extraction failed: %s, falling back to keyword", e)
            return self._extract_signals_keyword(text, stock)

    # ──────────────────────────────────────────────────────────────
    # Generate factor hypotheses from market narratives
    # ──────────────────────────────────────────────────────────────

    def generate_hypotheses(
        self,
        narrative: str,
        available_factors: list[str] | None = None,
        market_context: str = "",
    ) -> list[FactorHypothesis]:
        """Generate testable factor hypotheses from a market narrative.

        Args:
            narrative: Market narrative or thesis (e.g., "新能源板块资金持续流入")
            available_factors: Existing factors to check against
            market_context: Additional market context

        Returns:
            List of FactorHypothesis objects
        """
        if self.mode == "llm":
            return self._generate_hypotheses_llm(narrative, available_factors, market_context)
        return self._generate_hypotheses_keyword(narrative, available_factors)

    def _generate_hypotheses_keyword(
        self, narrative: str, available_factors: list[str] | None
    ) -> list[FactorHypothesis]:
        """Keyword-based hypothesis generation."""
        hypotheses = []

        # Map narrative themes to factor hypotheses
        theme_map = {
            "资金流入": ("turnover_20d", "资金流入驱动换手率上升，短期动量效应增强", 0.04),
            "业绩": ("roe", "业绩增长反映在ROE改善上，质量因子应有正IC", 0.035),
            "估值": ("pb_ratio", "估值修复推动低PB股票跑赢，价值因子有效", 0.03),
            "波动": ("volatility_60d", "市场波动加大，低波动异象更显著", 0.04),
            "动量": ("momentum_12m", "趋势延续，中期动量效应增强", 0.045),
            "规模": ("log_market_cap", "小盘股流动性改善，规模效应显现", 0.03),
            "政策": ("momentum_1m", "政策催化短期行情，1月动量效应增强", 0.035),
            "行业": ("amplitude_20d", "行业轮动加速，振幅因子能捕捉波动", 0.025),
        }

        for theme, (factor, logic, ic) in theme_map.items():
            if theme in narrative:
                if available_factors is None or factor in available_factors:
                    hypotheses.append(FactorHypothesis(
                        factor_name=factor,
                        description=f"{theme}主题下{factor}因子应有正向预测力",
                        expected_ic=ic,
                        economic_logic=logic,
                        data_requirements=["日频行情数据", "财务数据"],
                        risk_factors=["主题持续性不确定", "可能已被市场定价"],
                        confidence=0.5,
                    ))

        return hypotheses

    def _generate_hypotheses_llm(
        self, narrative: str, available_factors: list[str], market_context: str
    ) -> list[FactorHypothesis]:
        """LLM-based hypothesis generation."""
        prompt = f"""You are a quantitative researcher. Based on this market narrative, generate factor hypotheses.

Narrative: {narrative}
Available factors: {', '.join(available_factors) if available_factors else 'any'}
Market context: {market_context[:500]}

Generate 2-4 testable hypotheses as a JSON array. Each:
- factor_name: which factor to test
- description: one-line description
- expected_ic: expected IC magnitude (e.g., 0.03-0.06)
- economic_logic: why this should work (in Chinese)
- data_requirements: what data is needed
- risk_factors: what could go wrong
- confidence: 0-1

Output ONLY valid JSON array."""

        try:
            result = self._call_llm(prompt)
            data = json.loads(result)
            return [
                FactorHypothesis(
                    factor_name=item.get("factor_name", "unknown"),
                    description=item.get("description", ""),
                    expected_ic=item.get("expected_ic", 0.03),
                    economic_logic=item.get("economic_logic", ""),
                    data_requirements=item.get("data_requirements", []),
                    risk_factors=item.get("risk_factors", []),
                    confidence=item.get("confidence", 0.5),
                )
                for item in data if isinstance(item, dict)
            ]
        except Exception as e:
            logger.warning("LLM hypothesis generation failed: %s", e)
            return self._generate_hypotheses_keyword(narrative, available_factors)

    # ──────────────────────────────────────────────────────────────
    # Summarize attribution in natural language
    # ──────────────────────────────────────────────────────────────

    def summarize_attribution(
        self,
        factor_contributions: dict[str, float],
        daily_returns: pd.Series | None = None,
        period: str = "本月",
    ) -> str:
        """Generate a natural language summary of portfolio attribution.

        Args:
            factor_contributions: factor_name -> contribution (decimal)
            daily_returns: daily return series for context
            period: time period description

        Returns:
            Chinese natural language summary
        """
        if self.mode == "llm":
            return self._summarize_attribution_llm(factor_contributions, daily_returns, period)
        return self._summarize_attribution_keyword(factor_contributions, daily_returns, period)

    def _summarize_attribution_keyword(
        self,
        contributions: dict[str, float],
        daily_returns: pd.Series | None,
        period: str,
    ) -> str:
        """Keyword-based attribution summary."""
        lines = [f"【{period}组合归因分析】"]

        # Sort by absolute contribution
        sorted_factors = sorted(contributions.items(), key=lambda x: abs(x[1]), reverse=True)

        # Top positive contributors
        positives = [(k, v) for k, v in sorted_factors if v > 0]
        negatives = [(k, v) for k, v in sorted_factors if v < 0]

        if positives:
            lines.append("正贡献因子：" + "、".join(
                f"{k}(+{v*10000:.0f}bps)" for k, v in positives[:3]
            ))

        if negatives:
            lines.append("负贡献因子：" + "、".join(
                f"{k}({v*10000:.0f}bps)" for k, v in negatives[:3]
            ))

        # Performance context
        if daily_returns is not None and len(daily_returns) > 0:
            total_ret = (1 + daily_returns).prod() - 1
            vol = daily_returns.std() * np.sqrt(252)
            sharpe = (daily_returns.mean() * 252) / vol if vol > 0 else 0
            lines.append(f"期间收益：{total_ret:.2%}，年化波动：{vol:.2%}，夏普：{sharpe:.2f}")

        # Factor insight
        best_factor = sorted_factors[0] if sorted_factors else None
        if best_factor:
            lines.append(f"核心驱动因子：{best_factor[0]}，贡献{best_factor[1]*10000:.0f}bps")

        return "\n".join(lines)

    def _summarize_attribution_llm(
        self,
        contributions: dict[str, float],
        daily_returns: pd.Series | None,
        period: str,
    ) -> str:
        """LLM-based attribution summary."""
        context = ""
        if daily_returns is not None and len(daily_returns) > 0:
            total_ret = (1 + daily_returns).prod() - 1
            vol = daily_returns.std() * np.sqrt(252)
            context = f"期间收益：{total_ret:.2%}，年化波动率：{vol:.2%}"

        prompt = f"""用中文写一段简洁的组合归因分析（100字以内）。

{period}因子贡献（bps）：
{json.dumps({k: round(v*10000, 1) for k, v in contributions.items()}, ensure_ascii=False)}

{context}

要求：指出主要正/负贡献因子，分析原因，给出建议。"""

        try:
            return self._call_llm(prompt)
        except Exception:
            return self._summarize_attribution_keyword(contributions, daily_returns, period)

    # ──────────────────────────────────────────────────────────────
    # Risk narrative generation
    # ──────────────────────────────────────────────────────────────

    def describe_risk(
        self,
        risk_decomposition: dict[str, Any],
        regime: str = "neutral",
    ) -> str:
        """Generate a natural language risk report.

        Args:
            risk_decomposition: dict with total_risk, factor_risk, specific_risk, etc.
            regime: market regime (risk_on, neutral, cautious, risk_off)

        Returns:
            Chinese risk report
        """
        total = risk_decomposition.get("total_risk", 0)
        factor = risk_decomposition.get("factor_risk", 0)
        specific = risk_decomposition.get("specific_risk", 0)
        r_sq = risk_decomposition.get("r_squared", 0)

        regime_desc = {
            "risk_on": "市场风险偏好较高",
            "neutral": "市场状态中性",
            "cautious": "市场趋于谨慎",
            "risk_off": "市场避险情绪升温",
        }

        lines = ["【风险概况】"]
        lines.append(f"总风险：{total:.1%}（年化），其中因子风险{factor:.1%}，特异性风险{specific:.1%}")
        lines.append(f"模型解释度R²={r_sq:.1%}，{regime_desc.get(regime, '')}")

        # Factor exposures
        exposures = risk_decomposition.get("factor_exposures", {})
        if exposures:
            top_exposure = max(exposures.items(), key=lambda x: abs(x[1]))
            lines.append(f"最大因子暴露：{top_exposure[0]}（{top_exposure[1]:.3f}）")

        # Factor contributions
        contributions = risk_decomposition.get("factor_contributions", {})
        if contributions:
            top_contrib = max(contributions.items(), key=lambda x: abs(x[1]))
            lines.append(f"风险贡献最大因子：{top_contrib[0]}（{top_contrib[1]*10000:.0f}bps）")

        return "\n".join(lines)

    # ──────────────────────────────────────────────────────────────
    # Internal helpers
    # ──────────────────────────────────────────────────────────────

    def _call_llm(self, prompt: str) -> str:
        """Call OpenAI API with caching."""
        cache_key = hashlib.md5(prompt.encode()).hexdigest()
        if cache_key in self._cache:
            return self._cache[cache_key]

        from openai import OpenAI
        if self._client is None:
            self._client = OpenAI(api_key=self.api_key)

        response = self._client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=500,
            temperature=0.1,
        )
        result = response.choices[0].message.content.strip()
        self._cache[cache_key] = result
        return result

    @staticmethod
    def _chunk_text(text: str, max_chars: int = 2000) -> list[str]:
        """Split text into chunks respecting sentence boundaries."""
        if len(text) <= max_chars:
            return [text]

        chunks = []
        sentences = re.split(r'(?<=[。！？\n])', text)
        current = ""
        for sentence in sentences:
            if len(current) + len(sentence) > max_chars:
                if current:
                    chunks.append(current)
                current = sentence
            else:
                current += sentence
        if current:
            chunks.append(current)

        return chunks or [text[:max_chars]]

    @staticmethod
    def _keyword_sentiment(text: str) -> float:
        """Quick keyword sentiment score."""
        bullish = ["增长", "超预期", "利好", "增持", "突破", "创新", "复苏", "景气"]
        bearish = ["下降", "亏损", "减持", "违约", "风险", "收紧", "下跌", "危机"]

        b_count = sum(1 for w in bullish if w in text)
        s_count = sum(1 for w in bearish if w in text)
        total = b_count + s_count
        if total == 0:
            return 0.0
        return round((b_count - s_count) / total, 4)

    @staticmethod
    def _infer_factor_implications(metric: str, value: float) -> dict[str, float]:
        """Infer which factors are affected by a metric."""
        implications = {
            "revenue_growth": {"momentum_1m": 0.3, "roe": 0.2},
            "profit_growth": {"roe": 0.4, "momentum_3m": 0.2},
            "profit_decline": {"roe": -0.3, "momentum_1m": -0.2},
            "buyback": {"momentum_1m": 0.2, "volatility_20d": -0.1},
            "dividend_yield": {"pb_ratio": 0.2, "momentum_1m": 0.1},
        }
        return implications.get(metric, {})

    @staticmethod
    def _deduplicate_signals(signals: list[ExtractedSignal]) -> list[ExtractedSignal]:
        """Remove duplicate signals, keeping highest confidence."""
        seen: dict[str, ExtractedSignal] = {}
        for s in signals:
            key = f"{s.stock}_{s.signal_type}_{s.direction}"
            if key not in seen or s.confidence > seen[key].confidence:
                seen[key] = s
        return list(seen.values())
